export * from './queries/games';
export * from './queries/home';
export * from './queries/orders';
export * from './queries/profile';
export * from './queries/recommended';
export * from './queries/upcoming';
export * from './queries/wishlist';
export * from './mutations/register';
export * from './mutations/wishlist';
